name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Meson build
      uses: BSFishy/meson-build@v1.0.1
      with:
        action: build
        meson-version: 0.54.2
    - name: Run tests
      run: ./build/tests --color always
